version: "3.8"
services:
  postgres:
    image: postgres
    container_name: nyc-taxi
    environment:
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: dR4m%T6nb
      POSTGRES_DB: nyc_taxi
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: